import type { NextPage } from 'next';
import Head from 'next/head';
import Staking from '../components/Staking';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Elysia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Staking />
      </div>
    </>
  );
};

export default Home;
